theme: jekyll-theme-slate
title: Quorten Blog 1
description: First blog for all Quorten's blog-like writings
permalink: /blog/:year/:month/:day/:title/
#baseurl: "/quorten-blog1/" # the subpath of your site, e.g. /blog/

paginate: 10
paginate_path: "/blog/:num/"

recent_posts: 5
excerpt_link: "Read More"
titlecase: true
category_dir: blog/categories

plugins:
  - jekyll-paginate
  - jekyll-feed

authors:
  quorten:
    name: Andrew Makousky
    github: quorten
